#!/usr/bin/env node
/**
 * Reads the canonical index.html at the repo root and emits htmlContent.js
 * containing the entire HTML as a default-exported template-literal string,
 * so the Expo WebView can render it with `source={{ html }}` without any
 * runtime file I/O.
 */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'index.html');
const DST = path.join(__dirname, '..', 'htmlContent.js');

const html = fs.readFileSync(SRC, 'utf8');

// Escape characters that would break a template literal:
//   \  →  \\
//   `  →  \`
//   ${ →  \${
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const out =
  '// AUTO-GENERATED by scripts/build-html.js — do not edit by hand.\n' +
  '// Regenerate with `npm run build:html`.\n' +
  '/* eslint-disable */\n' +
  'export default `' + escaped + '`;\n';

fs.writeFileSync(DST, out);
console.log(`Wrote ${DST} (${out.length.toLocaleString()} bytes)`);
